/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserRouteImport } from './routes/users/$user'
import { Route as PostsPostRouteImport } from './routes/posts/$post'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserRoute = UsersUserRouteImport.update({
  id: '/users/$user',
  path: '/users/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostRoute = PostsPostRouteImport.update({
  id: '/posts/$post',
  path: '/posts/$post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/posts/$post': typeof PostsPostRoute
  '/users/$user': typeof UsersUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/posts/$post': typeof PostsPostRoute
  '/users/$user': typeof UsersUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/posts/$post': typeof PostsPostRoute
  '/users/$user': typeof UsersUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/posts/$post' | '/users/$user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/posts/$post' | '/users/$user'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/posts/$post'
    | '/users/$user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PostsPostRoute: typeof PostsPostRoute
  UsersUserRoute: typeof UsersUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$user': {
      id: '/users/$user'
      path: '/users/$user'
      fullPath: '/users/$user'
      preLoaderRoute: typeof UsersUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$post': {
      id: '/posts/$post'
      path: '/posts/$post'
      fullPath: '/posts/$post'
      preLoaderRoute: typeof PostsPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PostsPostRoute: PostsPostRoute,
  UsersUserRoute: UsersUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
